# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/edgar/Documentos/DUNE/Self_trigger/DAPHNE_V2a/xilinx/constraints.xdc

# IP: /home/edgar/Documentos/DUNE/Self_trigger/DAPHNE_V2a/ip/daphne2_daq_txonly/daphne2_daq_txonly.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==daphne2_daq_txonly || ORIG_REF_NAME==daphne2_daq_txonly} -quiet] -quiet

# IP: /home/edgar/Documentos/DUNE/Self_trigger/DAPHNE_V2a/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet
